### ISSUE TITLE
VocPub profile formats listing missing text/anot+turtle

### ISSUE THREAD

**Issue by lalewis1** [idn-au/catalogue-data#26]
looks like a prez-ui thing. 

prez returns the profile / mediatype in the headers correctly.
maybe prez ui is filtering out the rel=self.

looks like that is what is happening.

https://github.com/RDFLib/prez-ui/blob/781622441d0c2ecd60200088c0352e82c547cc61/src/composables/api.ts#L85

**Comment by lalewis1** [comment]
@jamiefeiss can you confirm that this is indeed what is happening here.

I'm not sure then if this is the intended functionality, if so then probably there is nothing to fix.

**Comment by lalewis1** [comment]
@jamiefeiss Did you get a chance to take a look at this yet?

**Comment by jamiefeiss** [comment]
It's not just Vocpub text/anot+turtle, Prez UI doesn't list the current mediatype on the right on any page. The line you linked shows that only the "alternate" link headers are listed.

It depends if we want to show the current media type, or show text/anot+turtle for any profile.

This can be fixed by simply including "self" or "alternate" in the code you linked.

**Comment by lalewis1** [comment]
OK, thanks. makes sense.

I suppose then its back on @nicholascar to confirm that this behavior is undesired.

I can see the logic in not including the current profile in the list of Alternate Profiles. but perhaps it is useful nonetheless to include it, such that the current profile view can be easily downloaded / saved to a file.

**Comment by lalewis1** [comment]
Discussed in the weekly IDN standup, current behaviour is acceptable.
